const data = [
	{
		_id: "1",
		name: "product1",
		image: "/images/img1.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 10.0,
		CountInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: "2",
		name: "product2",
		image: "/images/img2.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 10.0,
		CountInStock: 5,
		rating: 4.0,
		numReviews: 1,
	},
	{
		_id: "3",
		name: "product3",
		image: "/images/img3.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 5.0,
		CountInStock: 20,
		rating: 5.0,
		numReviews: 4,
	},
	{
		_id: "4",
		name: "product4",
		image: "/images/img4.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 10.0,
		CountInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: "5",
		name: "product5",
		image: "/images/img5.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 10.0,
		CountInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: "6",
		name: "product6",
		image: "/images/img6.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 10.0,
		CountInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: "7",
		name: "product7",
		image: "/images/img7.jpg",
		description: "description",
		brand: "brand",
		category: "category",
		price: 10.0,
		CountInStock: 0,
		rating: 2.5,
		numReviews: 12,
	},
];

export default data;
